export const dynamic = 'force-dynamic';
import { prisma } from '@/lib/prisma';
import { tagGroups } from '@/lib/constants';
import { generateAdvice, positionFromTags } from '@/lib/recommendation';
import { redirect } from 'next/navigation';
import { mem, uid } from '@/lib/memory-store';

async function create(formData: FormData) {'use server'; const tags=formData.getAll('tags').map(String); const dose=Number(formData.get('doseG')); const output=Number(formData.get('beverageOutputG')); const ratio=output/dose; const pos=positionFromTags(tags,ratio);
try {const brew=await prisma.brew.create({data:{coffeeId:String(formData.get('coffeeId')),grinderId:String(formData.get('grinderId')),brewMethod:String(formData.get('brewMethod')),grinderSetting:Number(formData.get('grinderSetting')),doseG:dose,beverageOutputG:output,waterInputG:Number(formData.get('waterInputG')),brewRatio:ratio,waterTempC:Number(formData.get('waterTempC')),brewTimeSec:Number(formData.get('brewTimeSec')),tastingNotes:String(formData.get('tastingNotes')||''),rating:Number(formData.get('rating')),notes:String(formData.get('notes')||''),followedPreviousAdvice:false,x:pos.x,y:pos.y}}); const advice=generateAdvice(tags,ratio); for(const rule of advice){await prisma.recommendation.create({data:{brewId:brew.id,...rule}})} redirect(`/brews/${brew.id}`)}
catch {const id=uid(); mem.brews.push({id,coffeeId:String(formData.get('coffeeId')),grinderId:String(formData.get('grinderId')),brewMethod:String(formData.get('brewMethod')),grinderSetting:Number(formData.get('grinderSetting')),doseG:dose,beverageOutputG:output,waterInputG:Number(formData.get('waterInputG')),brewRatio:ratio,waterTempC:Number(formData.get('waterTempC')),brewTimeSec:Number(formData.get('brewTimeSec')),tastingNotes:String(formData.get('tastingNotes')||''),rating:Number(formData.get('rating')),notes:String(formData.get('notes')||''),followedPreviousAdvice:false,previousBrewId:null,x:pos.x,y:pos.y,tastedAt:new Date()}); generateAdvice(tags,ratio).forEach(r=>mem.recs.push({id:uid(),brewId:id,variable:r.variable,direction:r.direction,stepSize:r.stepSize})); redirect(`/brews/${id}`)} }

export default async function NewBrew(){ let coffees:any[]=[]; let grinders:any[]=[]; let fallback=false; try{coffees=await prisma.coffee.findMany(); grinders=await prisma.grinder.findMany();}catch{fallback=true;coffees=mem.coffees;grinders=mem.grinders}
if(!coffees.length||!grinders.length) return <div className='card'><p>Add at least one coffee and grinder before logging a brew.</p></div>;
return <form action={create} className='space-y-4'><h1 className='text-xl'>New Brew Log</h1>{fallback&&<p className='text-amber-300'>Using in-memory mode.</p>}<div className='grid gap-3 md:grid-cols-3'><select name='coffeeId'>{coffees.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name='grinderId'>{grinders.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input name='brewMethod' required placeholder='Brew method'/><input name='grinderSetting' type='number' step='0.1' required placeholder='Grinder setting'/><input name='doseG' type='number' step='0.1' required placeholder='Dose g'/><input name='beverageOutputG' type='number' step='0.1' required placeholder='Output g'/><input name='waterInputG' type='number' step='0.1' required placeholder='Water g'/><input name='waterTempC' type='number' step='0.1' required placeholder='Temp °C'/><input name='brewTimeSec' type='number' required placeholder='Time sec'/><input name='rating' type='number' min='1' max='10' required placeholder='Rating'/><textarea name='tastingNotes' placeholder='Tasting notes'/><textarea name='notes' placeholder='Notes'/></div><div className='card'>{Object.entries(tagGroups).map(([k,t])=><div key={k}><p>{k}</p>{t.map(tag=><label key={tag}><input type='checkbox' name='tags' value={tag}/> {tag} </label>)}</div>)}</div><button className='rounded bg-emerald-700 px-3 py-2'>Save Brew</button></form>}
